# Generated by Django 5.0.2 on 2025-06-16 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="サロン名")),
                ("address", models.TextField(verbose_name="住所")),
                ("phone_number", models.CharField(max_length=15, verbose_name="電話番号")),
                ("email", models.EmailField(max_length=254, verbose_name="メールアドレス")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "opening_time",
                    models.TimeField(default="09:00", verbose_name="開店時間"),
                ),
                (
                    "closing_time",
                    models.TimeField(default="19:00", verbose_name="閉店時間"),
                ),
                (
                    "auto_assign_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="指名なし予約を自動でスタイリストに割り当てる",
                        verbose_name="自動割り当て有効",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_manager",
            field=models.BooleanField(
                default=False, help_text="店長として全スタッフを管理する権限", verbose_name="店長権限"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_owner",
            field=models.BooleanField(
                default=False, help_text="オーナーとして全権限を持つ", verbose_name="オーナー権限"
            ),
        ),
        migrations.CreateModel(
            name="StylistProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="自己紹介")),
                (
                    "experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="経験年数"),
                ),
                ("specialties", models.JSONField(default=list, verbose_name="得意分野")),
                (
                    "working_hours_start",
                    models.TimeField(default="09:00", verbose_name="勤務開始時間"),
                ),
                (
                    "working_hours_end",
                    models.TimeField(default="18:00", verbose_name="勤務終了時間"),
                ),
                (
                    "accepts_walk_ins",
                    models.BooleanField(
                        default=True,
                        help_text="指名なしの予約を受け付けるか",
                        verbose_name="指名なし予約受付",
                    ),
                ),
                (
                    "priority_level",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="自動割り当て時の優先度（数字が小さいほど優先）",
                        verbose_name="優先度",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="アクティブ")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "salon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylists",
                        to="accounts.salon",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_stylist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority_level", "user__first_name"],
            },
        ),
    ]
