# Generated by Django 5.0.2 on 2025-06-15 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="サービス名")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="所要時間（分）"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="料金"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="自己紹介")),
                (
                    "experience_years",
                    models.PositiveIntegerField(default=0, verbose_name="経験年数"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="予約受付中"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "services",
                    models.ManyToManyField(
                        blank=True, to="bookings.service", verbose_name="提供サービス（旧）"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateTimeField(verbose_name="予約日時")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RESERVED", "予約済み"),
                            ("PAID", "支払い済み"),
                            ("CANCELLED", "キャンセル"),
                            ("COMPLETED", "完了"),
                        ],
                        default="RESERVED",
                        max_length=10,
                    ),
                ),
                (
                    "requires_payment",
                    models.BooleanField(default=False, verbose_name="事前支払い要否"),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Stripe Payment Intent ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="合計金額"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.service",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="bookings.stylist",
                    ),
                ),
            ],
            options={
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="StylistService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="このスタイリストがこのサービスを行う際の所要時間",
                        verbose_name="この美容師での所要時間（分）",
                    ),
                ),
                (
                    "price_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="空白の場合はサービス標準価格を使用",
                        max_digits=10,
                        null=True,
                        verbose_name="価格上書き",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="提供可能"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_services",
                        to="bookings.service",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stylist_services",
                        to="bookings.stylist",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタイリストサービス",
                "verbose_name_plural": "スタイリストサービス",
                "unique_together": {("stylist", "service")},
            },
        ),
    ]
