# Generated by Django 5.0.2 on 2025-06-16 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100, verbose_name="顧客名")),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="顧客電話番号"),
                ),
                (
                    "customer_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="顧客メールアドレス"
                    ),
                ),
                ("appointment_date", models.DateTimeField(verbose_name="予約日時")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(verbose_name="所要時間（分）"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="備考")),
                (
                    "is_confirmed",
                    models.BooleanField(default=True, verbose_name="確定済み"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_manual_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.service",
                    ),
                ),
                (
                    "stylist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_appointments",
                        to="bookings.stylist",
                    ),
                ),
            ],
            options={
                "verbose_name": "手動予約",
                "verbose_name_plural": "手動予約",
                "ordering": ["-appointment_date"],
            },
        ),
        migrations.CreateModel(
            name="StylistBookingLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_code",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="ユニークコード"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="有効")),
                ("booking_url", models.URLField(blank=True, verbose_name="ブッキングURL")),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(default=30, verbose_name="最大事前予約日数"),
                ),
                (
                    "allow_guest_booking",
                    models.BooleanField(default=True, verbose_name="ゲスト予約を許可"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stylist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_link",
                        to="bookings.stylist",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタイリストブッキングリンク",
                "verbose_name_plural": "スタイリストブッキングリンク",
            },
        ),
    ]
